// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeachingAssignmentApp.Data;

#nullable disable

namespace TeachingAssignmentApp.Migrations
{
    [DbContext(typeof(TeachingAssignmentDbContext))]
    partial class TeachingAssignmentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TeachingAssignmentApp.Data.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ProfessionalGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProfessionalGroupId");

                    b.ToTable("Course");
                });

            modelBuilder.Entity("TeachingAssignmentApp.Data.ProfessionalGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("ProfessionalGroup");
                });

            modelBuilder.Entity("TeachingAssignmentApp.Data.Teacher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("GdInstruct")
                        .HasColumnType("float");

                    b.Property<double?>("GdTeaching")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teacher");
                });

            modelBuilder.Entity("TeachingAssignmentApp.Data.Course", b =>
                {
                    b.HasOne("TeachingAssignmentApp.Data.ProfessionalGroup", null)
                        .WithMany("ListCourse")
                        .HasForeignKey("ProfessionalGroupId");
                });

            modelBuilder.Entity("TeachingAssignmentApp.Data.ProfessionalGroup", b =>
                {
                    b.HasOne("TeachingAssignmentApp.Data.Teacher", null)
                        .WithMany("ListProfessional")
                        .HasForeignKey("TeacherId");
                });

            modelBuilder.Entity("TeachingAssignmentApp.Data.ProfessionalGroup", b =>
                {
                    b.Navigation("ListCourse");
                });

            modelBuilder.Entity("TeachingAssignmentApp.Data.Teacher", b =>
                {
                    b.Navigation("ListProfessional");
                });
#pragma warning restore 612, 618
        }
    }
}
